# Generated by Django 6.0.4 on 2026-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harsh_mevada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('internship', 'Internship Opportunity'), ('fresher', 'Fresher Job Role'), ('other', 'Other')], default='other', max_length=500),
        ),
    ]
